/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AccentColorsExpansionPanel_v1: typeof import('./components/AccentColorsExpansionPanel_v1.vue')['default']
    AccentColorsExpansionPanel_v2: typeof import('./components/AccentColorsExpansionPanel_v2.vue')['default']
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    AppHeaderNav: typeof import('./components/AppHeaderNav.vue')['default']
    AppPageHeader: typeof import('./components/AppPageHeader.vue')['default']
    ButtonVariantDisplayCard: typeof import('./components/ButtonVariantDisplayCard.vue')['default']
    ColorCodeDisplayCard: typeof import('./components/ColorCodeDisplayCard.vue')['default']
    CustomExpansionPanel: typeof import('./components/CustomExpansionPanel.vue')['default']
    GenericExpansionPanel: typeof import('./components/GenericExpansionPanel.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    ProfilePopoverMenu_LoggedIn: typeof import('./components/ProfilePopoverMenu_LoggedIn.vue')['default']
    ProfilePopoverMenu_LoggedOut: typeof import('./components/ProfilePopoverMenu_LoggedOut.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
