/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/Colors': RouteRecordInfo<'/Colors', '/Colors', Record<never, never>, Record<never, never>>,
    '/Counter': RouteRecordInfo<'/Counter', '/Counter', Record<never, never>, Record<never, never>>,
    '/Favorites': RouteRecordInfo<'/Favorites', '/Favorites', Record<never, never>, Record<never, never>>,
    '/Help': RouteRecordInfo<'/Help', '/Help', Record<never, never>, Record<never, never>>,
    '/Home': RouteRecordInfo<'/Home', '/Home', Record<never, never>, Record<never, never>>,
    '/Settings': RouteRecordInfo<'/Settings', '/Settings', Record<never, never>, Record<never, never>>,
    '/Test': RouteRecordInfo<'/Test', '/Test', Record<never, never>, Record<never, never>>,
  }
}
